/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;
import Clases.ClsConexion;
import Clases.ClsVentas;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author BRAYAN HERNADEZ
 */
public class FrmVentas extends javax.swing.JPanel {

    /**
     * Creates new form FrmVentas
     */
    
    ClsConexion conexion= new ClsConexion();
    ClsVentas ventas= new ClsVentas();
    
   
    float subtotal;

    public FrmVentas() {
        initComponents();
        comboboxTipo.setModel(ventas.getValues());
        comboboxTipo.setSelectedIndex(-1);
        lblNombre.setText("Prueba");
       
       // camarotes= new DefaultListModel();
       // listSelectCam.setModel(camarotes);
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdentidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoViaje = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        spinCantidadCam = new javax.swing.JSpinner();
        spinCantidadPer = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboboxTipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnAgregarCam = new javax.swing.JButton();
        btnEliminarCam = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDetalle = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblPuerto = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblRegreso = new javax.swing.JLabel();
        lblSalida = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        lblPortuario = new javax.swing.JLabel();
        lblisv = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblEmpleado1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(96, 203, 249));
        setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Identidad:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 27, -1, -1));

        txtIdentidad.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        add(txtIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 24, 280, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Codigo Viaje:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 27, -1, -1));

        txtCodigoViaje.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        add(txtCodigoViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 24, 280, -1));

        jPanel1.setBackground(new java.awt.Color(38, 151, 186));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Cantidad de Camarotes:");

        spinCantidadCam.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        spinCantidadPer.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Cantidad de Personas:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Tipo de Camarote:");

        comboboxTipo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        comboboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Camarotes Seleccionados:");

        btnAgregarCam.setBackground(new java.awt.Color(12, 69, 104));
        btnAgregarCam.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnAgregarCam.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCam.setText("Agregar");
        btnAgregarCam.setBorderPainted(false);
        btnAgregarCam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCamActionPerformed(evt);
            }
        });

        btnEliminarCam.setBackground(new java.awt.Color(12, 69, 104));
        btnEliminarCam.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnEliminarCam.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCam.setText("Eliminar");
        btnEliminarCam.setBorderPainted(false);
        btnEliminarCam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCamActionPerformed(evt);
            }
        });

        tableDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad Personas", "Cantidad Camarotes", "Tipo Camarote"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableDetalle);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(182, 182, 182)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spinCantidadCam, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(comboboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnAgregarCam)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarCam))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(spinCantidadPer, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinCantidadCam, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarCam)
                            .addComponent(btnEliminarCam))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(spinCantidadPer, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 59, 870, 210));

        jPanel2.setBackground(new java.awt.Color(38, 151, 186));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Descuento:");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setText("Impuesto Portuario:");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setText("Subtotal:");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Total:");

        lblPuerto.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblPuerto.setText("jLabel8");

        lblSubtotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblSubtotal.setText("lblSubtotal");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setText("Puerto Salida:");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setText("Impuesto Venta:");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel16.setText("Nombre Cliente:");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel17.setText("Nombre Empleado:");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel18.setText("Fecha Salida:");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel19.setText("Fecha Regreso:");

        lblRegreso.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblRegreso.setText("jLabel8");

        lblSalida.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblSalida.setText("jLabel8");

        lblNombre.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblNombre.setText("jLabel8");

        lblDescuento.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblDescuento.setText("jLabel8");

        lblPortuario.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblPortuario.setText("jLabel8");

        lblisv.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblisv.setText("lblIsv");

        lblTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTotal.setText("jLabel8");

        lblEmpleado1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblEmpleado1.setText("jLabel8");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(72, 72, 72)
                        .addComponent(lblSalida)
                        .addGap(408, 408, 408)
                        .addComponent(lblPortuario))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(52, 52, 52)
                        .addComponent(lblRegreso)
                        .addGap(197, 197, 197)
                        .addComponent(jLabel15)
                        .addGap(61, 61, 61)
                        .addComponent(lblisv))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(70, 70, 70)
                        .addComponent(lblPuerto)
                        .addGap(197, 197, 197)
                        .addComponent(jLabel11)
                        .addGap(164, 164, 164)
                        .addComponent(lblTotal))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137)
                                .addComponent(jLabel10)
                                .addGap(133, 133, 133)
                                .addComponent(lblSubtotal))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(109, 109, 109)
                                        .addComponent(lblDescuento))))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(lblNombre))
                    .addComponent(jLabel10)
                    .addComponent(lblSubtotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(lblEmpleado1)
                    .addComponent(jLabel8)
                    .addComponent(lblDescuento))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel18)
                    .addComponent(lblSalida)
                    .addComponent(lblPortuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(lblRegreso)
                    .addComponent(jLabel15)
                    .addComponent(lblisv))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(lblPuerto)
                    .addComponent(jLabel11)
                    .addComponent(lblTotal)))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 297, 868, 200));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Factura a Realizar");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 268, -1, -1));

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setText("Confirmar");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 506, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(96, 203, 249));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Vector (1).png"))); // NOI18N
        btnBuscar.setBorderPainted(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(873, 24, 30, 29));
    }// </editor-fold>//GEN-END:initComponents

  
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
      ventas.setIdentidad(txtIdentidad.getText());
      ventas.setCodigo_viaje(Integer.parseInt(txtCodigoViaje.getText()));
      ventas.infoViaje();
      lblNombre.setText(ventas.nombreCliente());
      lblPuerto.setText(ventas.getPuerto_salida());
      lblRegreso.setText(ventas.getFecha_regreso().toString());
      lblSalida.setText(ventas.getFecha_salida().toString());
      
         
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarCamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCamActionPerformed
        // TODO add your handling code here:
       ventas.setCantidad_camarotes((int)spinCantidadCam.getValue());
       ventas.setCantidad_personas((int)spinCantidadPer.getValue());
       ventas.setTipo_camarote(comboboxTipo.getSelectedItem().toString());
       
        DefaultTableModel  modelo= (DefaultTableModel) tableDetalle.getModel();
        modelo.addRow(new Object[]{String.valueOf(ventas.getCantidad_personas()),
          String.valueOf(ventas.getCantidad_camarotes()), ventas.getTipo_camarote()  });
        
        subtotal= subtotal+ventas.precioExtraer();
        lblSubtotal.setText(String.valueOf(subtotal));
        spinCantidadCam.setValue(0);
        spinCantidadPer.setValue(0);
        comboboxTipo.setSelectedIndex(-1);
    }//GEN-LAST:event_btnAgregarCamActionPerformed

    private void btnEliminarCamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCamActionPerformed
       
    }//GEN-LAST:event_btnEliminarCamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCam;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminarCam;
    private javax.swing.JComboBox<String> comboboxTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblEmpleado1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPortuario;
    private javax.swing.JLabel lblPuerto;
    private javax.swing.JLabel lblRegreso;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblisv;
    private javax.swing.JSpinner spinCantidadCam;
    private javax.swing.JSpinner spinCantidadPer;
    private javax.swing.JTable tableDetalle;
    private javax.swing.JTextField txtCodigoViaje;
    private javax.swing.JTextField txtIdentidad;
    // End of variables declaration//GEN-END:variables
}
